backend:
  name: git-gateway
  branch: master # Branch to update


  media_folder: "images"
  public_folder: "images"

collections:
    - name: "yogurt"
      label: "yogurt"
      folder: "yogurtshop"